#! /usr/bin/env node

const Client = require('ftp');
const argv = require('yargs').argv;

require('dotenv').config();

const lib = require('./lib');

const client = new Client();
const clientLib = lib(client);

client
	.on('greeting', console.log)
	.on('ready', () => {
		console.log('Client connection ready!');

		if (argv.upload) {
			return clientLib.put(argv.filePath, argv.fileName);
		}

		if (argv.download) {
			return clientLib.get(argv.fileName);
		}
	})
	.on('error', (...errors) => {
		console.log(JSON.stringify(errors, null, 2));
		process.exit(1);
	})
	.on('close', () => process.exit(0));

client.connect({
	host: process.env.FTP_HOST,
	user: process.env.FTP_USER,
	password: process.env.FTP_PASSWORD,
	keepalive: false
});
